### ISSUE TITLE
Catastrophic automatic save problem completely prevents auto-saving snippet changes

### ISSUE THREAD

**Issue by daniel347x** [carbon-app/carbon#1178]
**Describe the bug**

Creating a new snippet and pasting code saves automatically and successfully (the first time). Any and all changes made thereafter never save, but spit errors into the developer console. This is true both on Chrome and Firefox. Screenshot of error is provided.

**To Reproduce**

1. Load the website
2. Paste some code
3. Watch the "Saved" toast appear
4. Edit the code
5. The snippet is never saved thereafter
6. Note a slew of errors in the developer console (see screenshot of the first appearance of the error only, for clarity)

**Expected behavior**

The snippet should be saved automatically upon making edits, and no errors should appear in the developer console.

**Screenshot**

![image](https://user-images.githubusercontent.com/309746/109237873-78cb6380-77a0-11eb-8392-bfe377174d7c.png)

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: **Windows**
- Browser [e.g. Chrome, Safari, Firefox]: **Chrome**
- Carbon URL [e.g. carbon.now.sh?bg=pink]: **https://carbon.now.sh/**

**Comment by mfix22** [comment]
Huge apologies @daniel347x — there was some strange regression when we replaced `axios` with `redaxios` 😞 

It should be fixed now. Again, super sorry about this.

**Comment by marles77** [comment]
This is still an issue. Autosave is a nightmare. Some changes are saved some not (but mostly not, regardless the "Snippet saved" snackbar). However, no errors are reported in the console.

OS: Win 10
Browser: Chrome (99.0.4844.51), Firefox (98.0)

What I would also suggest is to add a  button "Save changes" for explicit save.

**Comment by mfix22** [comment]
I agree this is a better pattern. Working on this feature!
