### ISSUE TITLE
carbon.now.sh refused to connect.

### ISSUE THREAD

**Issue by matthaltom** [carbon-app/carbon#852]
**Describe the bug**
Our iframe code samples are not working. 

**To Reproduce**
Test any iframe embed. I copied one again from your site and it did not work.

**Expected behavior**
Loading of the code.

**Screenshots**
<img width="1014" alt="Screen Shot 2019-08-22 at 11 42 27 AM" src="https://user-images.githubusercontent.com/465097/63536975-f4749200-c4d1-11e9-85ed-1f425f8b6514.png">

**Info (please complete the following information):**

- OS [e.g. macOS, Linux, Windows, iOS]: Mac OS.
- Browser [e.g. chrome, safari]: Chrome
-

<details>
  <summary>Code Snippet (If Applicable)</summary>
  <pre>
  <iframe
  src="https://carbon.now.sh/embed/"
  style="transform:scale(0.7); width:1024px; height:473px; border:0; overflow:hidden;"
  sandbox="allow-scripts allow-same-origin">
</iframe>
  </pre>
</details>

**Comment by mfix22** [comment]
Sorry about that! The issue is fixed now 👍

**Comment by matthaltom** [comment]
The issue still persists but now the page is loading the website and not the iframed code. :( 

<img width="574" alt="Screen Shot 2019-08-22 at 12 16 19 PM" src="https://user-images.githubusercontent.com/465097/63539173-b62da180-c4d6-11e9-9b56-e34b17dc6ac6.png">

**Comment by matthaltom** [comment]
Live example here... https://www.blocknative.com/readiness-assessment

**Comment by mfix22** [comment]
Remove the trailing slash from `/embed/`. Should be `/embed`.

I'll try and get around to allowing `/embed/` right now though

**Comment by matthaltom** [comment]
Thank you. I've gone ahead and done that and it worked. Thanks for your prompt response!

**Comment by mfix22** [comment]
Great! I just fixed it on our end too. Thanks for understanding! Please let me know if you run into other issues 👍
